export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PURCAHSE_BURGER_START = 'PURCAHSE_BURGER_START';
export const PURCAHSE_BURGER_SUCCESS = 'PURCAHSE_BURGER_SUCCESS';
export const PURCAHSE_BURGER_FAIL= 'PURCAHSE_BURGER_FAIL';